.TH man 1 "07 Aug 2015" "1.0" "aptly-publisher man page"
.SH NAME
aptly\-publisher \- tool for easy creation of Aptly multi component publishes

.SH SYNOPSIS
.B aptly\-publisher
[-h] [-v] [-d] [--dry] --url URL [--recreate]
[-c CONFIG] [--source SOURCE] [--target TARGET]
[--components COMPONENTS [COMPONENTS ...]]
.IR action

.SH DESCRIPTION
.B aptly\-publisher
allows one to create aptly multi-component publishes from JSON definition of
repositories and mirrors

.SH ACTIONS
.TP
.B publish
will update publishes from repositories and mirrors defined in config
.TP
.B promote
will promote published snapshots of one publish to another
.TP
.B cleanup
will remove unused snapshots

.SH OPTIONS
.TP
\-c CONFIG, \-\-config CONFIG
Path to configuration YAML file
.TP
\-v, \-\-verbose
.TP
\-d, \-\-debug
.TP
\-h, \-\-help
.TP
\-\-recreate
Drop publish and create it again, only way to add new components
.TP
\-\-dry, \-\-dry\-run
.TP
\-\-url
URL to Aptly API, eg. http://localhost:8080
.TP
\-\-source
Source publish to take snapshots from (promote action)
.TP
\-\-target
Target publish to update (promote action)
.TP
\-\-components
Space-separated list components to promote (promote action)
.TP
\-\-diff
Show differences between publishes (promote action)

.SH BUGS
.TP
Determine source snapshots correctly
- at the moment it relies on snapshot comments that may not be reliable
- see https://github.com/smira/aptly/issues/271
.TP
Cleanup merged snapshots before cleaning up source ones.
 - so it's needed to run cleanup multiple times to clean up everything.

.SH AUTHOR
Filip Pytloun <filip.pytloun@tcpcloud.eu>

.SH COPYRIGHT
(C) 2015 tcp cloud
