#!/usr/bin/env python3

from PyQt5.QtCore import QStringListModel, Qt
from PyQt5.QtGui import QStandardItem, QStandardItemModel
from PyQt5.QtWidgets import (QApplication, QComboBox, QDataWidgetMapper,
                             QGridLayout, QLabel, QLineEdit, QMenuBar, QPushButton, QTextEdit, QWidget, QMainWindow,
                             QListView, QAbstractItemView, QAction, QTabWidget)

from aptly.publisher import Publish, PublishManager
from aptly.client import Aptly


class PublishTab(QWidget):

    def __init__(self, dataManager,parent=None):
        super(PublishTab, self).__init__(parent)

        self.dataManager = dataManager
        # initialize widgets
        self.repoBox = QComboBox()
        self.deleteButton = QPushButton("Delete")
        self.snapshotButton = QPushButton("Snapshot")
        self.minimalSnapshotButton = QPushButton("Minimal snapshot")
        self.packageLabel = QListView()
        self.packageLabel.setEditTriggers(QAbstractItemView.NoEditTriggers)

        # place widget in the layout
        layout = QGridLayout()
        layout.addWidget(self.repoBox, 0, 0, 1, 1)
        layout.addWidget(self.deleteButton, 0, 1, 1, 1)
        layout.addWidget(self.snapshotButton, 0, 2, 1, 1)
        layout.addWidget(self.minimalSnapshotButton, 1, 2, 1, 1)
        layout.addWidget(self.packageLabel, 1, 1, 2, 1)
        self.setLayout(layout)

        # initialize datas
        self.model = QStandardItemModel(self.packageLabel)
        self.repoDictionnary = {}
        # controllers
        self.loadRepository()
        self.repoBox.currentIndexChanged.connect(self.updateList)
        self.deleteButton.clicked.connect(self.removePackage)








